Repository KangHayeonn/pickplace-server, pull requests merged in 2023-08, with the labels that each got.

#81 [UPDATE] API 이슈
  src/main/java/com/server/pickplace/common/handler/GlobalExceptionHandler.java
  src/main/java/com/server/pickplace/config/SpringSecurityConfig.java
  src/main/java/com/server/pickplace/host/repository/HostRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/member/entity/Member.java
  src/main/java/com/server/pickplace/member/error/MembeExceptionHandler.java
  src/main/java/com/server/pickplace/member/error/MemberExceptionHandler.java
  src/main/java/com/server/pickplace/member/service/MemberService.java
  src/main/java/com/server/pickplace/place/entity/Place.java
  src/main/java/com/server/pickplace/place/entity/Room.java
  src/main/java/com/server/pickplace/place/entity/Unit.java
  src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
  src/main/java/com/server/pickplace/reservation/dto/PayRequest.java
  src/main/java/com/server/pickplace/reservation/entity/Reservation.java
  src/main/java/com/server/pickplace/reservation/error/ReservationErrorResult.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/search/dto/DetailPageRequest.java
  src/main/java/com/server/pickplace/search/dto/PlaceAddNumberResponse.java
  src/main/java/com/server/pickplace/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/search/service/SearchService.java
Labels: 🌈 update, ✋ code-review

#84 [UPDATE] 결제 도메인 관련 수정
  src/main/java/com/server/pickplace/reservation/service/ReservationService.java
Labels: 🌈 update

#86 [BUGFIX] : put, delete cors 이슈 해결
  src/main/java/com/server/pickplace/config/CommonConfig.java
  src/main/java/com/server/pickplace/config/SpringSecurityConfig.java
  src/main/java/com/server/pickplace/member/controller/MemberController.java
Labels: 🌈 update, 🐛 bug, ✋ code-review

#88 [UPDATE] QR 결제 관련 코드 수정
  src/main/java/com/server/pickplace/reservation/service/ReservationService.java
Labels: ✨ add, ✋ code-review

#89 [UPDATE] : 메일링 관련 기능 구현 & 예약/결제 API 수정 & cors 에러 해결
  build.gradle
  src/main/java/com/server/pickplace/common/handler/GlobalExceptionHandler.java
  src/main/java/com/server/pickplace/config/CommonConfig.java
  src/main/java/com/server/pickplace/config/SpringSecurityConfig.java
  src/main/java/com/server/pickplace/host/repository/HostRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/mailling/EmailConfig.java
  src/main/java/com/server/pickplace/mailling/controller/EmailController.java
  src/main/java/com/server/pickplace/mailling/dto/PassWordEditDto.java
  src/main/java/com/server/pickplace/mailling/service/EmailService.java
  src/main/java/com/server/pickplace/member/controller/MemberController.java
  src/main/java/com/server/pickplace/member/entity/Member.java
  src/main/java/com/server/pickplace/member/error/MembeExceptionHandler.java
  src/main/java/com/server/pickplace/member/error/MemberErrorResult.java
  src/main/java/com/server/pickplace/member/error/MemberExceptionHandler.java
  src/main/java/com/server/pickplace/member/repository/MemberRepository.java
  src/main/java/com/server/pickplace/member/service/MemberInfoService.java
  src/main/java/com/server/pickplace/member/service/MemberService.java
  src/main/java/com/server/pickplace/place/entity/Place.java
  src/main/java/com/server/pickplace/place/entity/Room.java
  src/main/java/com/server/pickplace/place/entity/Unit.java
  src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
  src/main/java/com/server/pickplace/reservation/dto/PayRequest.java
  src/main/java/com/server/pickplace/reservation/entity/Reservation.java
  src/main/java/com/server/pickplace/reservation/error/ReservationErrorResult.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/reservation/service/ReservationService.java
  src/main/java/com/server/pickplace/search/dto/DetailPageRequest.java
  src/main/java/com/server/pickplace/search/dto/PlaceAddNumberResponse.java
  src/main/java/com/server/pickplace/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/search/service/SearchService.java
  src/main/java/com/server/pickplace/socialLogin/kakao/service/KakaoUserService.java
  src/main/resources/templates/mail.html
Labels: 🌈 update, ♻ refactor, 🐛 bug, ✨ add
