Repository KangHayeonn/pickplace-server, pull requests merged in 2023-07, with the labels that each got.

#61 [UPDATE] MockUpData 이슈
  src/main/java/com/server/pickplace/search/config/SearchMockUpSetting.java
Labels: ⛏ ci/cd

#64 [UPDATE] MockUpData 이슈
  src/main/java/com/server/pickplace/search/config/SearchMockUpSetting.java
Labels: 🌈 update

#63 [UPDATE] API 관련 이슈들
  src/main/java/com/server/pickplace/search/controller/SearchController.java
Labels: 🌈 update

#55 [ADD] 결제/예약 도메인
  build.gradle
  src/main/java/com/server/pickplace/host/controller/HostController.java
  src/main/java/com/server/pickplace/host/dto/PlaceRequest.java
  src/main/java/com/server/pickplace/host/dto/PlaceRoomReqeuest.java
  src/main/java/com/server/pickplace/host/dto/RoomReqeust.java
  src/main/java/com/server/pickplace/host/dto/RoomResponse.java
  src/main/java/com/server/pickplace/host/error/HostErrorResult.java
  src/main/java/com/server/pickplace/host/repository/HostRepository.java
  src/main/java/com/server/pickplace/host/repository/HostRepositoryCustom.java
  src/main/java/com/server/pickplace/host/repository/HostRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/host/service/HostService.java
  src/main/java/com/server/pickplace/member/entity/Member.java
  src/main/java/com/server/pickplace/place/entity/Place.java
  src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
  src/main/java/com/server/pickplace/reservation/dto/AccountPayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/BankRequest.java
  src/main/java/com/server/pickplace/reservation/dto/BankResponse.java
  src/main/java/com/server/pickplace/reservation/dto/CardInfoResponse.java
  src/main/java/com/server/pickplace/reservation/dto/CardPayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/CardValidRequest.java
  src/main/java/com/server/pickplace/reservation/dto/MemberInfoResponse.java
  src/main/java/com/server/pickplace/reservation/dto/PayInfoResponse.java
  src/main/java/com/server/pickplace/reservation/dto/PayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/PlaceInfoResponse.java
  src/main/java/com/server/pickplace/reservation/dto/QRImageReqeust.java
  src/main/java/com/server/pickplace/reservation/dto/QRImageResponse.java
  src/main/java/com/server/pickplace/reservation/dto/QRPasswordRequest.java
  src/main/java/com/server/pickplace/reservation/dto/QRPayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/QRPriceResponse.java
  src/main/java/com/server/pickplace/reservation/entity/BankStatus.java
  src/main/java/com/server/pickplace/reservation/entity/QRPaymentInfomation.java
  src/main/java/com/server/pickplace/reservation/entity/QRStatus.java
  src/main/java/com/server/pickplace/reservation/entity/Reservation.java
  src/main/java/com/server/pickplace/reservation/error/ReservationErrorResult.java
  src/main/java/com/server/pickplace/reservation/error/ReservationException.java
  src/main/java/com/server/pickplace/reservation/error/ReservationExceptionHandler.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepository.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/reservation/service/ReservationService.java
  src/main/java/com/server/pickplace/search/controller/SearchController.java
  src/main/java/com/server/pickplace/search/repository/SearchRepositoryCustomImpl.java
  src/test/java/com/server/pickplace/search/Integration/BasicTest.java
Labels: ✨ add, ✋ code-review

#67 [ADD] 리뷰 도메인
  src/main/java/com/server/pickplace/common/common/BaseEntity.java
  src/main/java/com/server/pickplace/common/service/CommonService.java
  src/main/java/com/server/pickplace/config/CommonConfig.java
  src/main/java/com/server/pickplace/config/validation/Enum.java
  src/main/java/com/server/pickplace/config/validation/EnumValidator.java
  src/main/java/com/server/pickplace/host/config/HostConfig.java
  src/main/java/com/server/pickplace/host/controller/HostController.java
  src/main/java/com/server/pickplace/host/dto/PlaceRequest.java
  src/main/java/com/server/pickplace/host/dto/PlaceRoomReqeuest.java
  src/main/java/com/server/pickplace/host/dto/RoomReqeust.java
  src/main/java/com/server/pickplace/host/service/HostService.java
  src/main/java/com/server/pickplace/place/entity/Place.java
  src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
  src/main/java/com/server/pickplace/reservation/dto/AccountPayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/BankRequest.java
  src/main/java/com/server/pickplace/reservation/dto/CardPayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/CardValidRequest.java
  src/main/java/com/server/pickplace/reservation/dto/PayRequest.java
  src/main/java/com/server/pickplace/reservation/dto/QRImageReqeust.java
  src/main/java/com/server/pickplace/reservation/dto/QRPasswordRequest.java
  src/main/java/com/server/pickplace/reservation/dto/QRPayRequest.java
  src/main/java/com/server/pickplace/reservation/entity/Reservation.java
  src/main/java/com/server/pickplace/reservation/service/ReservationService.java
  src/main/java/com/server/pickplace/review/controller/ReviewController.java
  src/main/java/com/server/pickplace/review/dto/CreateReviewRequest.java
  src/main/java/com/server/pickplace/review/dto/PlaceReviewResponse.java
  src/main/java/com/server/pickplace/review/dto/ReviewDetailResponse.java
  src/main/java/com/server/pickplace/review/dto/ReviewResponse.java
  src/main/java/com/server/pickplace/review/dto/UpdateReviewRequest.java
  src/main/java/com/server/pickplace/review/entity/Review.java
  src/main/java/com/server/pickplace/review/error/ReviewErrorResult.java
  src/main/java/com/server/pickplace/review/error/ReviewException.java
  src/main/java/com/server/pickplace/review/error/ReviewExceptionHandler.java
  src/main/java/com/server/pickplace/review/repository/ReviewRepository.java
  src/main/java/com/server/pickplace/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/server/pickplace/review/repository/ReviewRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/review/service/ReviewService.java
  src/main/java/com/server/pickplace/search/controller/SearchController.java
  src/main/java/com/server/pickplace/search/dto/BasicSearchRequest.java
  src/main/java/com/server/pickplace/search/dto/CategorySearchRequest.java
  src/main/java/com/server/pickplace/search/dto/DetailPageRequest.java
  src/main/java/com/server/pickplace/search/dto/DetailSearchRequest.java
  src/main/java/com/server/pickplace/search/dto/NormalSearchRequest.java
  src/main/java/com/server/pickplace/search/dto/SearchRequest.java
  src/main/java/com/server/pickplace/search/entity/SearchType.java
  src/main/java/com/server/pickplace/search/error/SearchErrorResult.java
  src/main/java/com/server/pickplace/search/repository/SearchRepositoryCustom.java
  src/main/java/com/server/pickplace/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/server/pickplace/search/service/SearchService.java
  src/main/resources/messages/validation.properties
Labels: ✨ add, ✋ code-review

#73 [ADD] 예약 내역 조회/상세 조회 기능 추가
  src/main/java/com/server/pickplace/member/error/MemberErrorResult.java
  src/main/java/com/server/pickplace/member/service/MemberService.java
  src/main/java/com/server/pickplace/mypage/controller/MyPageController.java
  src/main/java/com/server/pickplace/mypage/dto/MyPageReservationMoreResponseDto.java
  src/main/java/com/server/pickplace/mypage/dto/MyPageReservationResponseDto.java
  src/main/java/com/server/pickplace/mypage/dto/PlaceAddressDto.java
  src/main/java/com/server/pickplace/mypage/repository/MyPageCategoryRepository.java
  src/main/java/com/server/pickplace/mypage/repository/MyPageReservationRepository.java
  src/main/java/com/server/pickplace/mypage/repository/MyPageReviewRepository.java
  src/main/java/com/server/pickplace/mypage/service/MyPageService.java
  src/main/java/com/server/pickplace/place/entity/Category.java
Labels: ✨ add, ✋ code-review
